sudo: required
services:
  - docker

deploy_services_job: &DEPLOY_SERVICE_JOB
  script:
    - cd ${TRAVIS_BUILD_DIR}/images/${SERVICE_PATH}
    - sed -i -e 's/APPD_HOST/$APPD_HOST/g' appdynamics.cfg
    - sed -i -e 's/APPD_ACCOUNT/$APPD_ACCOUNT/g' appdynamics.cfg
    - sed -i -e 's/APPD_ACCESSKEY/$APPD_ACCESSKEY/g' appdynamics.cfg
    - docker build -t ${APP_NAME} .

  after_success:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker tag ${APP_NAME} $DOCKER_USER/${APP_NAME}:$TRAVIS_BUILD_NUMBER
    - docker push $DOCKER_USER/${APP_NAME}:$TRAVIS_BUILD_NUMBER
    - docker tag ${APP_NAME} $DOCKER_USER/${APP_NAME}:latest
    - docker push $DOCKER_USER/${APP_NAME}:latest
    - cd -

jobs:
  include:
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy app1"
      env:
        -SERVICE_PATH="app1"
        -APP_NAME="flaskapp1"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy app2"
      env:
        -SERVICE_PATH="app2"
        -APP_NAME="flaskapp2"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy loadgen"
      env:
        -SERVICE_PATH="loadgen"
        -APP_NAME="loadgen"
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy pythonproxy"
      env:
        -SERVICE_PATH="pythonproxy"
        -APP_NAME="pythonproxy"