apiVersion: v1
data:
  APPDYNAMICS_AGENT_APPLICATION_NAME: NodejsApp3
  APPDYNAMICS_AGENT_ACCOUNT_NAME: customer1
  APPDYNAMICS_CONTROLLER_HOST_NAME: k8scluster-2072nosshco-g87xdpws.appd-sales.com
  APPDYNAMICS_CONTROLLER_PORT: 8090
  APPDYNAMICS_CONTROLLER_SSL_ENABLED: false
  APPDYNAMICS_AGENT_REUSE_NODE_NAME_PREFIX: njs
  APPDYNAMICS_AGENT_NODE_NAME: nodejs # not used in node name but required by Node.js agent
  APPDYNAMICS_LOGGER_OUTPUT_TYPE: console
  NODE_OPTIONS: '--require /opt/appdynamics/shim.js'
  # variables required to send transaction analytics data
kind: ConfigMap
metadata:
  name: appd-nodejs-config