apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: proxy
          image: noureddined123/pythonproxy
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
          volumeMounts:
          - name: shared-data
            mountPath: /tmp/appd/run
        - name: flask
          image: noureddined123/flaskapp1:latest
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
            - name: APPD_NODE_NAME
              value: ["$(HOSTNAME)"]
          volumeMounts:
          - name: shared-data
            mountPath: /tmp/appd/run
          ports:
          - containerPort: 5000
      restartPolicy: Always
      volumes:
      - name: shared-data
        emptyDir: {}
