apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: noureddined123/pythonproxy
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
          volumeMounts:
          - mountPath: "/tmp/appd/run"
            name: task-pv-storage
      restartPolicy: Always
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
