apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: noureddined123/pythonproxy
          imagePullPolicy: Always
          env:
            - name: APPD_PROXY_CONTROL_PATH
              value: /tmp/appd/run
          volumeMounts:
          - mountPath: /tmp/appd/run
            name: persistent-storage
      restartPolicy: Always
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: nfs
