apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: ec2-54-213-222-32.us-west-2.compute.amazonaws.com
    path: "/var/appd"