FROM ubuntu:16.04


RUN apt-get update -y && \
    apt-get install -y python-pip python-dev curl

# We copy just the requirements.txt first to leverage Docker cache
COPY ./requirements.txt /app/requirements.txt
COPY ./appdynamics.cfg /etc/appdynamics.cfg

WORKDIR /app

RUN pip install -r requirements.txt

COPY . /app


CMD ["/bin/bash", "startenv.sh" ]